BEGIN TRANSACTION;

DROP TABLE IF EXISTS "quiz";

DROP TABLE IF EXISTS "category";

CREATE TABLE IF NOT EXISTS "category" (
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name" TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "quiz" (
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"cat_id" INTEGER NOT NULL,
	"question" TEXT NOT NULL UNIQUE,
	"options" TEXT NOT NULL,
	"answer" TEXT NOT NULL,
	FOREIGN KEY("cat_id") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

COMMIT;